#include "gcodegenerator.h"
#include <QTextStream>
#include <cmath>
#include <algorithm>
#include <QDebug>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

GCodeGenerator::GCodeGenerator() {}

QVector<DispensePoint> GCodeGenerator::generateDispensePoints(const GerberLayer &layer) {
    QVector<DispensePoint> points;
    m_boundingRect = layer.boundingRect;

    // Для каждого полигона вычисляем центр и диаметр
    for (const QPolygonF &poly : layer.polygons) {
        if (poly.size() < 3) continue;

        // Центр полигона (барицентр)
        QPointF center;
        double area = 0.0;
        for (int i = 0; i < poly.size(); ++i) {
            int j = (i + 1) % poly.size();
            double cross = poly[i].x() * poly[j].y() - poly[j].x() * poly[i].y();
            area += cross;
            center += (poly[i] + poly[j]) * cross;
        }
        area /= 2.0;
        if (fabs(area) < 0.001) continue;
        center /= (6.0 * area);

        // Диаметр вписанной окружности
        double minDist = 1e9;
        for (const QPointF &pt : poly) {
            double d = sqrt(pow(pt.x() - center.x(), 2) + pow(pt.y() - center.y(), 2));
            minDist = qMin(minDist, d);
        }
        double diameter = qMax(minDist * 2.0, 0.1);

        DispensePoint dp;
        dp.position = QPointF(center.x() + m_offsetX, center.y() + m_offsetY);
        dp.diameter = diameter;
        dp.dispenseTime = calculateDispenseTime(diameter);
        dp.height = m_zDown;

        points.append(dp);
    }

    // Сортируем для оптимального пути (по X, потом по Y)
    std::sort(points.begin(), points.end(), [](const DispensePoint &a, const DispensePoint &b) {
        if (fabs(a.position.y() - b.position.y()) > 1.0)
            return a.position.y() < b.position.y();
        return a.position.x() < b.position.x();
    });

    qDebug() << "Generated" << points.size() << "dispense points";
    return points;
}

QString GCodeGenerator::generateGCode(const QVector<DispensePoint> &points, const QString &comment) {
    QString result;
    QTextStream out(&result);

    out << "; ===== G-CODE FOR PASTE DISPENSER =====\n";
    out << "; Generated by Gerber_Parser\n";
    if (!comment.isEmpty()) out << "; " << comment << "\n";
    out << "; \n";
    out << "; Points: " << points.size() << "\n";
    out << "; Feed rate: " << m_feedRate << " mm/min\n";
    out << "; Z up: " << m_zUp << " mm\n";
    out << "; Z down: " << m_zDown << " mm\n";
    out << "; Dwell time: " << m_dwellTime << " ms\n";
    out << "; =====================================\n";
    out << "\n";

    // Настройка
    out << "G21 ; Units in mm\n";
    out << "G90 ; Absolute positioning\n";
    out << "G00 Z" << formatCoord(m_zUp) << " ; Raise Z\n";
    out << "G00 X0 Y0 ; Go to origin\n";
    out << "M03 S100 ; Start pump\n";
    out << "G04 P500 ; Wait for pump\n";
    out << "\n";

    // Обход всех точек
    for (int i = 0; i < points.size(); ++i) {
        const DispensePoint &dp = points[i];

        // Переход к точке на высоте
        out << "; Point " << (i + 1) << " - diameter: " << dp.diameter << " mm\n";
        out << "G00 Z" << formatCoord(m_zUp) << "\n";
        out << "G00 X" << formatCoord(dp.position.x())
            << " Y" << formatCoord(dp.position.y()) << "\n";

        // Опускание
        out << "G01 Z" << formatCoord(dp.height)
            << " F" << formatCoord(m_feedRate / 2) << "\n";
        // Включить клапан
        out << "M07 ; Valve ON\n";

        // Дозирование
        out << "G04 P" << dp.dispenseTime << "\n";
        // Выключить клапан
        out << "M09 ; Valve OFF\n";

        // Подъём
        out << "G00 Z" << formatCoord(m_zUp) << "\n";
    }

    // Завершение
    out << "\n";
    out << "M05 ; Stop pump\n";
    out << "G00 X0 Y0 ; Return to origin\n";
    out << "G00 Z" << formatCoord(m_zUp) << "\n";
    out << "M02 ; End of program\n";

    return result;
}

double GCodeGenerator::calculateDispenseTime(double diameter) const {
    // Эмпирическая формула: время пропорционально площади
    double area = M_PI * (diameter / 2.0) * (diameter / 2.0);
    double time = m_dwellTime * (area / (M_PI * 0.25));  // относительно эталонной точки 0.5мм
    return qBound(50, (int)time, 2000);
}

QString GCodeGenerator::formatCoord(double value) const {
    return QString::number(value, 'f', 3);
}
