#include "gcodegenerator.h"
#include <QTextStream>
#include <cmath>
#include <algorithm>
#include <QDebug>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

namespace {

double distPointToSegment(const QPointF& p, const QPointF& a, const QPointF& b) {
    const double abx = b.x() - a.x();
    const double aby = b.y() - a.y();
    const double apx = p.x() - a.x();
    const double apy = p.y() - a.y();
    const double ab2 = abx * abx + aby * aby;
    if (ab2 < 1e-18) return std::hypot(apx, apy);
    double t = (apx * abx + apy * aby) / ab2;
    t = qBound(0.0, t, 1.0);
    const double cx = a.x() + t * abx;
    const double cy = a.y() + t * aby;
    return std::hypot(p.x() - cx, p.y() - cy);
}

/** Минимальное расстояние от точки до сторон многоугольника (отрезки). */
double minDistPointToPolygonEdges(const QPointF& c, const QPolygonF& poly) {
    double m = 1e9;
    const int n = poly.size();
    for (int i = 0; i < n; ++i) {
        const QPointF& a = poly[i];
        const QPointF& b = poly[(i + 1) % n];
        m = qMin(m, distPointToSegment(c, a, b));
    }
    return m;
}

double minDistPointToVertices(const QPointF& c, const QPolygonF& poly) {
    double m = 1e9;
    for (const QPointF& pt : poly)
        m = qMin(m, std::hypot(pt.x() - c.x(), pt.y() - c.y()));
    return m;
}

/**
 * Полигон с почти одинаковым расстоянием вершин до c (как у круга, аппроксимированного N отрезками).
 * Тогда диаметр = 2 * R по вершинам, а не по апофеме (расстоянию до хорды).
 */
bool isApproxCircularAbout(const QPointF& c, const QPolygonF& poly, double relTol = 0.02) {
    if (poly.size() < 8) return false;
    double r0 = -1.0;
    for (const QPointF& pt : poly) {
        const double ri = std::hypot(pt.x() - c.x(), pt.y() - c.y());
        if (r0 < 0) r0 = ri;
        else if (std::fabs(ri - r0) > qMax(0.01, relTol * r0)) return false;
    }
    return r0 > 1e-6;
}

} // namespace

GCodeGenerator::GCodeGenerator() {}

QVector<DispensePoint> GCodeGenerator::generateDispensePoints(const GerberLayer &layer) {
    QVector<DispensePoint> points;
    m_boundingRect = layer.boundingRect;

    // Для каждого полигона вычисляем центр и диаметр
    for (const QPolygonF &poly : layer.polygons) {
        if (poly.size() < 3) continue;

        // Центр полигона (барицентр)
        QPointF center;
        double area = 0.0;
        for (int i = 0; i < poly.size(); ++i) {
            int j = (i + 1) % poly.size();
            double cross = poly[i].x() * poly[j].y() - poly[j].x() * poly[i].y();
            area += cross;
            center += (poly[i] + poly[j]) * cross;
        }
        area /= 2.0;
        if (fabs(area) < 0.001) continue;
        center /= (6.0 * area);

        /*
         * Раньше диаметр брался как 2 * (мин. расстояние до вершин). Для прямоугольного падa это
         * половина диагонали, а не размер по меньшей стороне. Корректнее для вписанного круга
         * в центроиде: минимум расстояний до *рёбер*. Для круглого флэша (многоугольник по кругу)
         * расстояние до рёбер = апофема < R, поэтому если вершины лежат почти на одной окружности,
         * используем радиус по вершинам (= диаметр апертуры).
         */
        const double rEdge = minDistPointToPolygonEdges(center, poly);
        const double rVert = minDistPointToVertices(center, poly);
        const double effR = isApproxCircularAbout(center, poly) ? rVert : rEdge;
        const double diameter = qMax(2.0 * effR, 0.1);

        DispensePoint dp;
        dp.position = QPointF(center.x() + m_offsetX, center.y() + m_offsetY);
        dp.diameter = diameter;
        dp.dispenseTime = calculateDispenseTime(diameter);
        dp.height = m_zDown;

        points.append(dp);
    }

    // Сортируем для оптимального пути (по X, потом по Y)
    std::sort(points.begin(), points.end(), [](const DispensePoint &a, const DispensePoint &b) {
        if (fabs(a.position.y() - b.position.y()) > 1.0)
            return a.position.y() < b.position.y();
        return a.position.x() < b.position.x();
    });

    qDebug() << "Generated" << points.size() << "dispense points";
    return points;
}

QString GCodeGenerator::generateGCode(const QVector<DispensePoint> &points, const QString &comment) {
    return generateGCode(points, nullptr, comment);
}

QString GCodeGenerator::generateGCode(const QVector<DispensePoint> &points, QVector<GCodePointMap>* pointMap, const QString &comment) {
    QString result;
    QTextStream out(&result);

    int line = 0; // 0-based
    auto writeLine = [&](const QString& s) {
        out << s << "\n";
        ++line;
    };

    if (pointMap) pointMap->clear();

    writeLine("; ===== G-CODE FOR PASTE DISPENSER =====");
    writeLine("; Generated by Gerber_Parser");
    if (!comment.isEmpty()) writeLine("; " + comment);
    writeLine("; ");
    writeLine(QString("; Points: %1").arg(points.size()));
    writeLine(QString("; Feed rate: %1 mm/min").arg(m_feedRate));
    writeLine(QString("; Z up: %1 mm").arg(m_zUp));
    writeLine(QString("; Z down: %1 mm").arg(m_zDown));
    writeLine(QString("; Dwell time: %1 ms").arg(m_dwellTime));
    writeLine("; =====================================");
    writeLine("");

    // Настройка
    writeLine("G21 ; Units in mm");
    writeLine("G90 ; Absolute positioning");
    writeLine(QString("G00 Z%1 ; Raise Z").arg(formatCoord(m_zUp)));
    writeLine("G00 X0 Y0 ; Go to origin");
    writeLine("M03 S100 ; Start pump");
    writeLine("G04 P500 ; Wait for pump");
    writeLine("");

    // Обход всех точек
    for (int i = 0; i < points.size(); ++i) {
        const DispensePoint &dp = points[i];
        GCodePointMap map;

        map.startLine = line;
        writeLine(QString("; Point %1 - diameter: %2 mm").arg(i + 1).arg(dp.diameter));
        writeLine(QString("G00 Z%1").arg(formatCoord(m_zUp)));

        map.xyLine = line;
        writeLine(QString("G00 X%1 Y%2").arg(formatCoord(dp.position.x())).arg(formatCoord(dp.position.y())));

        // Опускание
        writeLine(QString("G01 Z%1 F%2").arg(formatCoord(dp.height)).arg(formatCoord(m_feedRate / 2)));
        // Включить клапан
        writeLine("M07 ; Valve ON");

        // Дозирование
        const int dwell = (dp.dispenseTime > 0) ? (int)dp.dispenseTime : (int)calculateDispenseTime(dp.diameter);
        writeLine(QString("G04 P%1").arg(dwell));
        // Выключить клапан
        writeLine("M09 ; Valve OFF");

        // Подъём
        writeLine(QString("G00 Z%1").arg(formatCoord(m_zUp)));

        map.endLine = line - 1;
        if (pointMap) pointMap->push_back(map);
    }

    // Завершение
    writeLine("");
    writeLine("M05 ; Stop pump");
    writeLine("G00 X0 Y0 ; Return to origin");
    writeLine(QString("G00 Z%1").arg(formatCoord(m_zUp)));
    writeLine("M02 ; End of program");

    return result;
}

double GCodeGenerator::computeDispenseTime(double diameter) const {
    return calculateDispenseTime(diameter);
}

double GCodeGenerator::calculateDispenseTime(double diameter) const {
    // Эмпирическая формула: время пропорционально площади
    double area = M_PI * (diameter / 2.0) * (diameter / 2.0);
    double time = m_dwellTime * (area / (M_PI * 0.25));  // относительно эталонной точки 0.5мм
    return qBound(50, (int)time, 2000);
}

QString GCodeGenerator::formatCoord(double value) const {
    return QString::number(value, 'f', 3);
}
